name: Pull Request Linting

on: pull_request

permissions:
  contents: read

env:
  CI: true

jobs:
  pr_lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.1

      - name: Use Bun.sh
        uses: oven-sh/setup-bun@v2.2.0
        with:
          bun-version: 1.4.2

      - name: Cache bun install cache
        uses: actions/cache@v6.1.0
        with:
          path: '~/.bun/install/cache'
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}

      - name: Install
        run: bun install --frozen-lockfile

      - name: Lint code
        run: bun run lint
